name: PHP Composer

on:
  push:
    branches: [ github-actions-ci-pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: drupal_codequality 
      uses: docker://hussainweb/drupalqa:php7.4
      with:
        cmd: |
          composer validate 
          phplint --no-cache -v web/modules/custom/ 
          phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ web/modules/custom 
          phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ web/modules/custom 
          phpmd web/modules/custom/ text phpmd.xml
     

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
